name: build node app
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: set up node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Lint and fix 
        run: npm run lint --fix

      - name: Test
        run: npm run test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref =='refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
    
      - name: set up node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy to Vercel
        run:  |
          echo "Deploy"
